name: Deploy Microservice
description: 'Deploy Microservice to an Environment on Planton Cloud'

inputs:
  planton_cloud_environment_name:
    description: 'name of the target environment on planton cloud.'
    required: true
  planton_cloud_microservice_instance_version:
    description: 'microservice-instance version i.e main or review-<pull-request-number>'
    required: true
  container_image_tag:
    description: 'version(commit-short-shar or tag) of the docker image to be used for tagging and publishing the image'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy Microservice
      run: planton microservice deploy --env-name ${{ inputs.planton_cloud_environment_name }} --version ${{ inputs.planton_cloud_microservice_instance_version }} --container-image-tag ${{ inputs.container_image_tag }}
      shell: bash
